### ISSUE TITLE
About C5 dataset, searched everywhere, but still cannot find where to download the c5 dataset.

### ISSUE THREAD

**Issue by zhaoqyu** [CaptainEven/MCMOT-ByteTrack#12]
It seems the chechpoint file worked very well in your demo video (which belong to C5 dataset),  but not working great in VisDrone dataset. Can you pls tell us where to download the C5 Dataset, cause I really cannot find this dataset .

Thanks for your kindness

**Comment by CaptainEven** [comment]
@LOVELACE01 Sorry, I'm not autherized(or permitted) to release the dataset.
