### ISSUE TITLE
max_id_dict.npz

### ISSUE THREAD

**Issue by stephenivy12** [CaptainEven/MCMOT-ByteTrack#14]
Hi,
where can I get max_id_dict.npz?
![image](https://user-images.githubusercontent.com/63568856/162367254-d7f144be-310e-4804-bc00-a5538592f253.png)

**Comment by CaptainEven** [comment]
[MCMOT-ByteTrack](https://github.com/CaptainEven/MCMOT-ByteTrack)/[datasets](https://github.com/CaptainEven/MCMOT-ByteTrack/tree/DarknetCfg/datasets)/max_id_dict.npz
