### ISSUE TITLE
How can I train with custom datasets?

### ISSUE THREAD

**Issue by ipolash** [CaptainEven/MCMOT-ByteTrack#19]
Can you help me to train custom datasets with more than 5 classes? I've tried train_track.py but got this error:
```
2022-05-17 14:38:21 | INFO     | yolox.data.datasets.mcmotdataset:37 - Classes: car, bicycle, person, cyclist, tricycle
2022-05-17 14:38:21 | ERROR    | yolox.data.datasets.mcmotdataset:48 - Invalid img root root: ..\dataset\train/JPEGImages
```

But, my dataset's classes are different what it mentioned. How to fix this? I think it's because of dataset load failure.

**Comment by ipolash** [comment]
Do you use this dataset for training?
http://aiskyeye.com/download/multi-object-tracking_2021/

**Comment by CaptainEven** [comment]
@ipolash You can refer to another epo of mine:
https://github.com/CaptainEven/MCMOT
It contains tutorial, python scripts and demo for Visdrone, may be what you want.

**Comment by ipolash** [comment]
Thank You. Now, I've prepared the dataset for training. But couldn't generate [max_id_dict.npz](https://github.com/CaptainEven/MCMOT-ByteTrack/blob/DarknetCfg/datasets/max_id_dict.npz)

Please help.

**Comment by CaptainEven** [comment]
First, you need to genearate the max_id_dict from the training dataset you want to train on(of course, parsing it first), then write it to disk for future using:
```
    with open(dict_path, "wb") as f:
        np.savez(dict_path, max_id_dict=max_id_dict)
```
If you will not train the ReID branch, you just do not need to generate  the max_id_dict file at all, only train a conventional detector will be enough for you.

**Comment by ipolash** [comment]
Thanks for your response. How to generate the max_id_dict from the training dataset? Please help.

**Comment by CaptainEven** [comment]
@ipolash You need to parse every sample fro the training dataset, and count the max id for each object class. You can refer to:
https://github.com/CaptainEven/MCMOT/blob/master/src/gen_dataset_visdrone.py, line164 for example.

**Comment by ipolash** [comment]
Thank You. I've actually used this script for dataset preparation. Thank You again for your prompt reply.

**Comment by ipolash** [comment]
Hi Even,
Thanks for your guide. I've successfully load the visdrone datasets. But, now I'm facing this error:
```
2022-05-19 15:20:58 | INFO     | yolox.core.trainer:206 - ---> start train epoch1
shape '[16, 1, 15, 56, 96]' is invalid for input of size 860160
```
It says invalid for input size. My current class no is 10.
Please help.

**Comment by ipolash** [comment]
In case, you need more info.
```
output = output.view(batch_size, self.n_anchors, n_ch, hsize, wsize)
             │      │    │           │    │          │     │      └ 96
             │      │    │           │    │          │     └ 56
             │      │    │           │    │          └ 15
             │      │    │           │    └ 1
             │      │    │           └ YOLOXDarknetReID(
             │      │    │               (module_list): ModuleList(
             │      │    │                 (0): Sequential(
             │      │    │                   (Conv2d): Conv2d(3, 24, kernel_size=(3, 3), stride=...
             │      │    └ 16
             │      └ <method 'view' of 'torch._C._TensorBase' objects>
             └ tensor([[[[-7.0374e-02,  2.3010e-02, -4.7119e-01,  ..., -4.5117e-01,
                          -4.1357e-01, -4.8975e-01],
                         [-4.2725...

RuntimeError: shape '[16, 1, 15, 56, 96]' is invalid for input of size 860160
```
