### ISSUE TITLE
Error during demo track

### ISSUE THREAD

**Issue by ArthurHakobyann** [CaptainEven/MCMOT-ByteTrack#2]
I try to run demo track with this code 
`python3 tools/demo_track.py -f exps/example/mot/yolox_x_mix_det.py -c pretrained/bytetrack_x_mot17.pth.tar --fp16 --fuse --save_result /content/MCMOT-ByteTrack`
but get this error
```
Traceback (most recent call last):
  File "tools/demo_track.py", line 480, in <module>
    main(exp, args)
  File "tools/demo_track.py", line 442, in main
    model.load_state_dict(ckpt["model"])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOX:
	size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([1, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([5, 320, 1, 1]).
	size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([5]).
	size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([1, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([5, 320, 1, 1]).
	size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([5]).
	size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([1, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([5, 320, 1, 1]).
	size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([5]).
```

**Comment by Tetsujinfr** [comment]
I think it is due to the pretrained model from bytetrack that you are using, which has only 1 class, while I guess here @CaptainEven  has tuned the code to process a pretrained model with 5 classes.

What is missing in the repo, I think, is the pretrained model so that a demo can be ran easily.

@CaptainEven please correct if inaccurate.

**Comment by ArthurHakobyann** [comment]
@Tetsujinfr  I dont find pretrained model with 5 classes․ Where is it?

**Comment by Tetsujinfr** [comment]
> @Tetsujinfr I dont find pretrained model with 5 classes․ Where is it?

I do not know neither, hence asking to @CaptainEven

**Comment by CaptainEven** [comment]
@Tetsujinfr @ArthurHakobyann Hi, the weights checkpoints has been updatated.
Sorry for the delay baecause of Chinese Lunar New Year.

**Comment by CaptainEven** [comment]
@Tetsujinfr @ArthurHakobyann Please use the DarknetCfg Branch for demo testing.

**Comment by Tetsujinfr** [comment]
> @Tetsujinfr @ArthurHakobyann Please use the DarknetCfg Branch for demo testing.

Thanks @CaptainEven 

Any chance you could put the weights onto gdrive as well as pan baidu? I do not want to install the baidu download malware on my machine.
Thanks
