### ISSUE TITLE
No class_id in the output

### ISSUE THREAD

**Issue by nwoyecid** [CaptainEven/MCMOT-ByteTrack#21]
I excepted a multi-class multi-object tracking.
However, the output format is save_format = '{frame},{id},{x1},{y1},{w},{h},{s},-1,-1,-1\n'
which takes no account of the category id of the object, like in your YOLOV4_MCMOT.

Is this MCMOT or MOT?

**Comment by CaptainEven** [comment]
@nwoyecid it's MCMOT. I do not write the txt results at the moment, you need to do that yourself now. I have updated function write_results_dict in demo_mcmot.py, you can do it yourself if needed.

**Comment by nwoyecid** [comment]
Thank you for your response.

I had to go through the code for understand where to modify to output both the track and class identities as in MCMOT. 
In the byte_tracker.py, I noticed you implement an update_mcmot_byte() function which is where the class identities are considered during tracking. However, this function is not used by the tracker. Instead, the update() function is used which only implements single class MOT. It is not straightforward how MCMOT is done using the byte_tracker or how it can be updated in your demo_mcmot.py file here. Please, throw more light.
