### ISSUE TITLE
More details on how to run the demo_mcmot.py demo?

### ISSUE THREAD

**Issue by Tetsujinfr** [CaptainEven/MCMOT-ByteTrack#3]
hi @CaptainEven 

could you give a bit more guidance on how to run the demo with REID on the 5 classes pretrained model ?
thanks

**Comment by CaptainEven** [comment]
@Tetsujinfr Hi, the weights checkpoints has been updatated.
Sorry for the delay baecause of Chinese Lunar New Year.

**Comment by Tetsujinfr** [comment]
Hi @CaptainEven 

so I managed to get the code running but I have some strange results.
On the test13 video, the results I get are not so good I think, with a lot of IDs where the ID changes for one to another while there is no occlusion happening.

https://user-images.githubusercontent.com/29961693/163299592-9e08df17-cd80-4f65-9c06-413084dda141.mp4


Here is another video where the results are completely off:

https://user-images.githubusercontent.com/29961693/163299866-338d5069-aec8-42fd-b1cc-d606313db58c.mp4


Here is my test command (I did move the test demo file at the repo root and changed the cfg path accordingly):
`python3 demo_mcmot.py --reid True -f exps/example/mot/yolox_tiny_track_c5_darknet.py --ckpt weights/latest_ckpt.pth.tar --path /home/tetsfr/Videos/video1.mp4`

What am I doing wrong?
thanks for your help

**Comment by Zhangyongtao123** [comment]
> hi @CaptainEven
> 
> could you give a bit more guidance on how to run the demo with REID on the 5 classes pretrained model ? thanks

Hi, Can you run the demo correctly now?
If so, could you please give me some guidance?

**Comment by Tetsujinfr** [comment]
@Zhangyongtao123 no unfortunately I did not push further. Hopefully @CaptainEven can give us a bit morr guidance on how to reproduce the 5 classes results or highlight the piece of code which needs to be tweaked to make sure the 5 classes are recognized properly on frames in the wild.

**Comment by Ronales** [comment]
11

**Comment by Ronales** [comment]
> Hi @CaptainEven
> 
> so I managed to get the code running but I have some strange results. On the test13 video, the results I get are not so good I think, with a lot of IDs where the ID changes for one to another while there is no occlusion happening.
> 
>  2022_04_14_02_51_10_low.mp4 
> Here is another video where the results are completely off:
> 
>  2022_04_14_02_55_28_low.mp4 
> Here is my test command (I did move the test demo file at the repo root and changed the cfg path accordingly): `python3 demo_mcmot.py --reid True -f exps/example/mot/yolox_tiny_track_c5_darknet.py --ckpt weights/latest_ckpt.pth.tar --path /home/tetsfr/Videos/video1.mp4`
> 
> What am I doing wrong? thanks for your help

I guess your setting is “tracker = byte” and "reid = true", you should note that based bytetracker set the detection thresh is 0.001, so maybe a lot of False positives will be apparent, so you should adjust this parameter such as 0.5.
