### ISSUE TITLE
Reid for other objects 

### ISSUE THREAD

**Issue by abhigoku10** [CaptainEven/MCMOT-ByteTrack#5]
@CaptainEven thanks for sharing the code base had few queries 
1. the current code base supports reid for only person ?
2. can we extend this reid principle to objects and vehicles also ? if so what all changes have to be made 

Thanks in advance

**Comment by CaptainEven** [comment]
@abhigoku10 The Repo supports multi-class ReID as many as the number of object classes you want to train.

**Comment by nwoyecid** [comment]
@CaptainEven  I looked at the output format of each track object, it doesn't account for different categories:
save_format = '{frame},{id},{x1},{y1},{w},{h},{s},-1,-1,-1\n' The category id is fixed to -1
How do you make this multi-class?
